/**
 * Naive UI — SSR/CSR unified plugin.
 *
 * On the server, collects CSS-in-JS styles generated by Naive UI components
 * and injects them into the HTML <head> to prevent flash of unstyled content
 * (FOUC) and avoid hydration mismatches.
 *
 * @see https://www.naiveui.com/en-US/os-theme/docs/ssr
 */
import { setup } from "@css-render/vue3-ssr";

export default defineNuxtPlugin((nuxtApp) => {
  if (import.meta.server && nuxtApp.ssrContext) {
    const { collect } = setup(nuxtApp.vueApp);
    const originalRenderMeta = nuxtApp.ssrContext.renderMeta;
    nuxtApp.ssrContext.renderMeta = async (): Promise<Record<string, string>> => {
      const originalMeta =
        typeof originalRenderMeta === "function" ? await originalRenderMeta() : {};
      return {
        ...(originalMeta as Record<string, string>),
        headTags: ((originalMeta as Record<string, string>).headTags ?? "") + collect(),
      };
    };
  }
});
